language: python
python: 
   - "3.2"
   - "3.3"

install:
   - "pip install -r requirements.txt"

script: nosetests

notifications:
   email: false
   irc:
      channels:
         - "chat.freenode.net#mochify"
      use_notice: true
      skip_join: true
      template:
         - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
         - "Commit view : %{compare_url}"

